import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import pandaLogo from "@assets/chow_chow_2_1774332948261.png";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary mb-8" data-testid="link-back-home">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <div className="flex items-center gap-3 mb-8">
          <img src={pandaLogo} alt="Marlow" className="w-16 h-16 object-contain" />
          <span className="font-display font-bold text-2xl tracking-tight">Marlow</span>
        </div>

        <h1 className="text-3xl font-bold font-display mb-2" data-testid="text-page-title">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Effective Date: February 28, 2026</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed">
          <p>
            These Terms govern your use of Marlow, operated by 말로교육 주식회사 (Marlow Education Co., Ltd.).
          </p>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">1. Eligibility</h2>
            <p>You must be 18 years or older to use this service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">2. Description of Service</h2>
            <p>Tone Coach provides pronunciation feedback for Mandarin learners based on submitted voice recordings.</p>
            <p className="mt-2">Feedback may be human-generated and/or generated by internal systems.</p>
            <p className="mt-2">We do not guarantee specific learning outcomes.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">3. User Content & License</h2>
            <p>You retain ownership of your voice recordings.</p>
            <p className="mt-2 mb-2">By uploading recordings, you grant us a non-exclusive, worldwide license to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Store</li>
              <li>Process</li>
              <li>Analyze</li>
              <li>Use recordings to provide feedback</li>
              <li>Improve and develop our services, including internal AI systems</li>
            </ul>
            <p className="mt-3">We will not sell your recordings.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">4. Subscriptions & Billing</h2>
            <p>Subscriptions are billed monthly and renew automatically unless canceled.</p>
            <p className="mt-2">Payments are processed through Stripe.</p>
            <p className="mt-2">You may cancel at any time. Cancellation stops future renewals but does not refund prior payments unless required by law.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">5. Refund Policy</h2>
            <p>Refunds are provided at our discretion unless required by applicable law.</p>
            <p className="mt-2">If you reside in the European Union, you may have a statutory 14-day withdrawal right unless you waive it by beginning service immediately.</p>
            <p className="mt-2">By subscribing and accessing the service immediately, you acknowledge that service begins upon purchase.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">6. Account Termination</h2>
            <p className="mb-2">We may suspend or terminate accounts that:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Violate these Terms</li>
              <li>Abuse the service</li>
              <li>Engage in unlawful behavior</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, the Company shall not be liable for indirect, incidental, or consequential damages arising from use of the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold font-display mt-8 mb-3">8. Governing Law</h2>
            <p>These Terms are governed by the laws of the Republic of Korea.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
