import { db } from "../db";
import { pronunciationErrors } from "@shared/schema";

const SEED_ERRORS = [
  // ─── TONES ────────────────────────────────────────────────────────────────
  {
    id: "T001",
    category: "tone" as const,
    commonError: "Tone 3 pronounced as full dip in all contexts",
    example: "好吃",
    scientificExplanation: "Tone 3 has a low-dipping contour (214), but in connected speech, the T3 often becomes low-tone (21).",
    simpleExplanation: "You're making every 3rd tone full dip, which sounds unnatural in sequences.",
    howToFix: "Learn tone sandhi rules: first 3rd tone in a sequence is pronounced as low tone.\n\nOnly fully dip isolated 3rd tones.",
    minimalPairs: "很棒, 好吃, 火鸡, 脑袋",
    practiceWords: ["很棒", "好吃", "火鸡", "脑袋"],
    isCustom: false,
  },
  {
    id: "T002",
    category: "tone" as const,
    commonError: "Tone 2 not rising enough",
    example: "麻",
    scientificExplanation: "Tone 2 is a rising tone (35). Learners often underuse pitch movement.",
    simpleExplanation: "Your pitch is too flat, so it doesn't sound like Tone 2.",
    howToFix: "Exaggerate the rise in pitch.\n\nStart from mid-level, end high.",
    minimalPairs: "麻烦, 朋友, 买菜",
    practiceWords: ["麻烦", "朋友", "买菜"],
    isCustom: false,
  },
  {
    id: "T003",
    category: "tone" as const,
    commonError: "Tone 4 not falling sharply enough",
    example: "骂",
    scientificExplanation: "Tone 4 is falling (51). Learners may under-articulate the fall.",
    simpleExplanation: "Your voice doesn't drop fast enough, making the tone sound weak.",
    howToFix: "Start high, drop quickly to low.\n\nThink of saying a short command.",
    minimalPairs: "骂人, 大学, 看书",
    practiceWords: ["骂人", "大学", "看书"],
    isCustom: false,
  },
  {
    id: "T004",
    category: "tone" as const,
    commonError: "Tone duration too short",
    example: "中国",
    scientificExplanation: "Tones last the duration of a syllable. It needs to be held until the next syllable is uttered.",
    simpleExplanation: "Your syllables are too fast and short.",
    howToFix: "Slow down.\n\nHold each tone slightly longer while keeping pitch contour correct.",
    minimalPairs: "中国, 学中文, 我的朋友",
    practiceWords: ["中国", "学中文", "我的朋友"],
    isCustom: false,
  },
  {
    id: "T005",
    category: "tone" as const,
    commonError: "Neutral tone stressed too strongly",
    example: "妈妈",
    scientificExplanation: "Neutral tone is unstressed / toneless, and shorter and softer than the syllable that precedes it.",
    simpleExplanation: "You're giving it too much stress, making it sound like a full tone.",
    howToFix: "Reduce pitch and duration.\n\nSay it quickly, lightly.",
    minimalPairs: "妈妈, 朋友们, 小孩子, 东西",
    practiceWords: ["妈妈", "朋友们", "小孩子", "东西"],
    isCustom: false,
  },
  {
    id: "T006",
    category: "tone" as const,
    commonError: "Tone 1 too flat or low",
    example: "妈",
    scientificExplanation: "Tone 1 is high-level (55), a long and held out flat tone. Learners sometimes produce it too low or uneven.",
    simpleExplanation: "Your voice is too low; tone doesn't sound bright.",
    howToFix: "Raise pitch.\n\nKeep level across syllable.",
    minimalPairs: "妈, 飞机",
    practiceWords: ["妈", "飞机"],
    isCustom: false,
  },
  {
    id: "T007",
    category: "tone" as const,
    commonError: "Tone 4 starting too low",
    example: "大 (dà)",
    scientificExplanation: "Tone 4 should start high (5) and fall. Starting low reduces contrast.",
    simpleExplanation: "Voice starts too low → falling tone is less sharp.",
    howToFix: "Begin high and drop quickly.",
    minimalPairs: "大, 去哪儿",
    practiceWords: ["大", "去哪儿"],
    isCustom: false,
  },
  {
    id: "T008",
    category: "tone" as const,
    commonError: "Tone 2 starting too high",
    example: "来",
    scientificExplanation: "Tone 2 rises from mid (3) → high (5). Starting too high reduces perceptual rise.",
    simpleExplanation: "Starts near the top → rise isn't noticeable.",
    howToFix: "Start mid-pitch, rise to high.",
    minimalPairs: "麻, 猴",
    practiceWords: ["麻", "猴"],
    isCustom: false,
  },
  {
    id: "T009",
    category: "tone" as const,
    commonError: "Tone sandhi ignored in 3rd tone sequences",
    example: "很好",
    scientificExplanation: "Tone sandhi: when two Tone 3's are in a row → first becomes Tone 2, but is faster and shorter than a regular Tone 2.",
    simpleExplanation: "You're not adjusting tones in sequences.",
    howToFix: "Apply tone sandhi: first Tone 3 becomes a short Tone 2.",
    minimalPairs: "你好, 老师好, 买东西",
    practiceWords: ["你好", "老师好", "买东西"],
    isCustom: false,
  },
  {
    id: "T010",
    category: "tone" as const,
    commonError: "Tone 3 is too high",
    example: "手",
    scientificExplanation: "Tone 3 should fall to low before rising slightly. Starting too high reduces dip effect.",
    simpleExplanation: "Voice starts high → dip is not interpreted as Tone 3.",
    howToFix: "Start low, dip slightly, then rise if isolated.",
    minimalPairs: "手, 好吗",
    practiceWords: ["手", "好吗"],
    isCustom: false,
  },
  {
    id: "T011",
    category: "tone" as const,
    commonError: "Tone 3 doesn't dip as it should",
    example: "宝",
    scientificExplanation: "Tone 3 is low-dipping (214). Flat low removes contour.",
    simpleExplanation: "Tone may sound like Tone 2 → causing confusion.",
    howToFix: "Drop pitch low, then rise for isolated tone.\n\nExaggerate in practice.",
    minimalPairs: "马, 买, 反",
    practiceWords: ["马", "买", "反"],
    isCustom: false,
  },
  {
    id: "T012",
    category: "tone" as const,
    commonError: "不 (bù) tone sandhi error",
    example: "不",
    scientificExplanation: "Mandarin 不 /bù/ is normally 4th tone (falling).\n\nWhen followed by another 4th tone, it changes to 2nd tone (rising) due to tone sandhi.\n\nMany learners ignore the rule and pronounce it as 4th tone in all contexts.",
    simpleExplanation: "\"不\" is like a casual \"shape-shifter\" tone: normally falling, but it rises before another falling tone.\n\nIf you don't change it, it sounds harsh or robotic.",
    howToFix: "Identify if the next word is 4th tone.\n\nIf so, change 不 from 4th (falling) → 2nd (rising).\n\nKeep the following 4th tone intact.",
    minimalPairs: "不对, 不是, 不大",
    practiceWords: ["不对", "不是", "不大"],
    isCustom: false,
  },
  {
    id: "T013",
    category: "tone" as const,
    commonError: "一 (yī) tone sandhi error",
    example: "一",
    scientificExplanation: "Mandarin 一 /yī/ is normally 1st tone (high-level).\n\nTone sandhi rules:\nBefore a 4th tone: 一 → 2nd tone (rising)\nBefore 1st, 2nd, 3rd tone: 一 → 4th tone (falling)\n\nLearners often leave it as 1st tone in all cases, causing unnatural pitch patterns.",
    simpleExplanation: "Think of 一 as a \"chameleon tone\": it changes based on the next word's tone.\n\nIt's only pronounced as Tone 1 when it's by itself or used as a strict numeral.",
    howToFix: "Listen to the tone of the next syllable.\n\nApply the rule:\nNext syllable 4th tone → 一 = 2nd tone\nNext syllable 1st/2nd/3rd → 一 = 4th tone\n\nPractice sequences slowly, then speed up.",
    minimalPairs: "一大早, 一个人, 一张纸",
    practiceWords: ["一大早", "一个人", "一张纸"],
    isCustom: false,
  },

  // ─── INITIALS ─────────────────────────────────────────────────────────────
  {
    id: "I001",
    category: "initial" as const,
    commonError: "Retroflex zh/ch/sh pronounced like j/q/x",
    example: "知 (zhī) vs 鸡 (jī)",
    scientificExplanation: "Mandarin retroflex affricates and fricatives (zh/ch/sh) require the tongue tip curled slightly back toward the hard palate.\n\nLearners often flatten the tongue forward, producing alveolo-palatal sounds (j/q/x) instead.",
    simpleExplanation: "Your tongue is too forward, making the sound softer and more like \"j/q/x\".",
    howToFix: "Curl the tip of your tongue slightly toward the roof of your mouth.\n\nMaintain the airflow over the tongue tip for fricatives or through the affricate for zh/ch.\n\nKeep lips neutral.",
    minimalPairs: "zhī / jī\nchī / qī\nshī / xī",
    practiceWords: ["知道", "吃饭", "是"],
    isCustom: false,
  },
  {
    id: "I002",
    category: "initial" as const,
    commonError: "q pronounced like English ch",
    example: "七 (qī)",
    scientificExplanation: "Mandarin q /tɕʰ/ is a voiceless aspirated alveolo-palatal affricate, produced with the tongue closer to the hard palate, unlike English \"ch /tʃ/\".",
    simpleExplanation: "Your tongue is too far back, making it sound like \"ch\".",
    howToFix: "Smile slightly to push the tongue forward.\n\nRelease air strongly to create aspiration.",
    minimalPairs: "qi qi qi\nchi chi chi\nqi → ch contrast",
    practiceWords: ["七", "去", "请"],
    isCustom: false,
  },
  {
    id: "I003",
    category: "initial" as const,
    commonError: "x pronounced like English sh",
    example: "西 (xī)",
    scientificExplanation: "Mandarin x /ɕ/ is a voiceless alveolo-palatal fricative, produced with the tongue high and front, unlike English \"sh /ʃ/\".",
    simpleExplanation: "You're producing a sound too far back, like \"sh\" in English.",
    howToFix: "Keep tongue high and forward near the palate.\n\nPush air gently through the teeth without curling the tongue tip.",
    minimalPairs: "xi / shi\nxiāng / shiāng",
    practiceWords: ["西", "小", "心"],
    isCustom: false,
  },
  {
    id: "I004",
    category: "initial" as const,
    commonError: "Mandarin r pronounced like English r",
    example: "人 (rén)",
    scientificExplanation: "Mandarin r /ʐ/ is a retroflex fricative, voiced, with the tongue tip curled slightly back.\n\nEnglish /r/ is an approximant, not a fricative.",
    simpleExplanation: "Your tongue isn't curled enough and the sound lacks friction.",
    howToFix: "Curl tongue tip slightly back.\n\nPush air through while voicing.\n\nAvoid English \"r\" glide.",
    minimalPairs: "r r r\nrén rén rén\nzhī → r contrast",
    practiceWords: ["人", "热", "日"],
    isCustom: false,
  },
  {
    id: "I005",
    category: "initial" as const,
    commonError: "c pronounced like English ts",
    example: "次 (cì)",
    scientificExplanation: "Mandarin c /tsʰ/ is a voiceless aspirated alveolar affricate.\n\nLearners often produce a sound that is either too unaspirated or incorrectly fronted like English \"ts\", which can make it sound flat or weak.",
    simpleExplanation: "You're saying the \"c\" too much like English \"ts,\" so it sounds flat or weak.\n\nIn Mandarin, c is a crisp, aspirated sound: start with a \"t\" and release it into \"s\" with a puff of air.",
    howToFix: "Place the tip of your tongue against your upper teeth ridge (alveolar ridge).\n\nStart with a light t-like stop, then immediately release into s.\n\nMake sure the air comes out sharply — that's the aspiration.\n\nAvoid English-style blending or voicing.",
    minimalPairs: "cì / sī\ncā / sā\ncā / kā (contrast with unaspirated k)",
    practiceWords: ["次", "草", "菜"],
    isCustom: false,
  },
  {
    id: "I006",
    category: "initial" as const,
    commonError: "z pronounced like English z",
    example: "走 (zǒu)",
    scientificExplanation: "Mandarin z /ts/ is a voiceless alveolar affricate: a stop + fricative combination.\n\nEnglish z /z/ is a voiced fricative, produced continuously without a stop.\n\nMany learners replace Mandarin z with English \"z\", making it sound too smooth, voiced, or \"buzzing,\" rather than the crisp \"t-s\" sound required.",
    simpleExplanation: "In English \"z,\" your vocal cords vibrate and you just let the air flow.\n\nIn Mandarin z, you should start with a quick \"t\" and release it into \"s,\" without voicing.\n\nThink of it as a very short \"ts\" puff, not buzzing like a bee.",
    howToFix: "Place your tongue tip behind your upper teeth (alveolar ridge).\n\nMake a light t-stop, then release into s.\n\nKeep it voiceless (don't vibrate your vocal cords).\n\nPush a little air through the fricative to make it crisp.",
    minimalPairs: "zì / sī\nzǎo / sǎo\nzài / sài",
    practiceWords: ["走", "字", "再"],
    isCustom: false,
  },
  {
    id: "I007",
    category: "initial" as const,
    commonError: "j pronounced too strongly like English j",
    example: "鸡 (jī)",
    scientificExplanation: "Mandarin j /tɕ/ is a voiceless alveolo-palatal affricate, produced with tongue body close to the hard palate.\n\nEnglish \"j /dʒ/\" is a voiced postalveolar affricate, with more voicing and stronger closure.\n\nLearners often over-voice or over-articulate, making Mandarin \"j\" sound like English \"dji,\" which is too harsh and incorrect.",
    simpleExplanation: "You're pronouncing Mandarin j too much like English \"j.\"\n\nIn Mandarin, it should sound lighter, softer, and unaspirated, without extra \"d\" or buzzing.",
    howToFix: "Place your tongue close to the hard palate (just behind upper teeth).\n\nStart with a light unvoiced closure, do not add a \"d\" sound.\n\nRelease air gently; no extra voicing.\n\nKeep lips neutral.",
    minimalPairs: "jī / dji (English-style \"j\")\njiā / dja",
    practiceWords: ["鸡", "家", "叫"],
    isCustom: false,
  },
  {
    id: "I008",
    category: "initial" as const,
    commonError: "b/p aspiration contrast not clear",
    example: "八 (bā) vs 趴 (pā)",
    scientificExplanation: "Mandarin contrasts unaspirated /b/ vs aspirated /pʰ/.\n\nb /b/ is voiceless unaspirated; minimal puff of air.\n\np /pʰ/ is voiceless aspirated; strong burst of air.\n\nLearners often under-aspirate p or over-voice b, making them indistinguishable.",
    simpleExplanation: "Your \"b\" and \"p\" sound too much alike.\n\nMandarin cares about air puff, not just voicing.\n\nThink: b = soft, p = strong air puff.",
    howToFix: "b: place lips together, release softly, almost like saying \"buh\" lightly.\n\np: place lips together, release with strong puff of air, like a small burst.\n\nKeep tongue position neutral and don't over-voice.\n\nOptional: hold a small piece of paper in front of your lips; it should move with p but not b.",
    minimalPairs: "bā / pā\nbó / pō\nbèi / pèi",
    practiceWords: ["八", "趴", "报", "跑"],
    isCustom: false,
  },
  {
    id: "I009",
    category: "initial" as const,
    commonError: "sh pronounced too weakly",
    example: "山",
    scientificExplanation: "Mandarin sh /ʂ/ is a voiceless retroflex fricative: tongue tip slightly curled back, air flows through a narrow gap to create friction.\n\nWhen weak, learners produce a sound closer to s /s/ or a very soft hiss, which loses the retroflex quality.",
    simpleExplanation: "Your \"sh\" is too soft, so it sounds like \"s\" in English.\n\nMandarin \"sh\" should be full, buzzing, and retroflex.",
    howToFix: "Curl your tongue tip slightly back toward the roof of your mouth (retroflex).\n\nPush air steadily through the narrow gap.\n\nDo not move your lips too much; keep them neutral.\n\nMake sure your vocal cords do not vibrate (voiceless).",
    minimalPairs: "shī / sī\nshǎo / sǎo\nshí / sí",
    practiceWords: ["是", "十", "少"],
    isCustom: false,
  },
  {
    id: "I010",
    category: "initial" as const,
    commonError: "sh pronounced too strongly",
    example: "山",
    scientificExplanation: "Mandarin sh /ʂ/ is a voiceless retroflex fricative, produced with the tongue tip slightly curled back and steady airflow.\n\nOver-articulation causes the sound to be harsh, overly loud, or distorted, which is unnatural and can be tiring to produce.",
    simpleExplanation: "You're overdoing \"sh,\" making it sound like a harsh hiss.\n\nIn Mandarin, \"sh\" should be crisp but smooth, not aggressive.",
    howToFix: "Relax your tongue tip slightly while keeping the retroflex curl.\n\nModerate the airflow; don't push too much air.\n\nKeep the lips neutral.\n\nFocus on smooth friction rather than loudness.",
    minimalPairs: null,
    practiceWords: ["是", "什么", "山"],
    isCustom: false,
  },

  // ─── FINALS ───────────────────────────────────────────────────────────────
  {
    id: "F001",
    category: "final" as const,
    commonError: "ü pronounced like u",
    example: "绿 (lǜ)",
    scientificExplanation: "Mandarin ü /y/ is a high front rounded vowel.\nLearners often replace it with u /u/, which is a back rounded vowel.",
    simpleExplanation: "Your tongue is too far back in your mouth.",
    howToFix: "Say \"ee\" (i). Keep your tongue in the same place. Now round your lips. That produces ü.",
    minimalPairs: "lu / lü\nnu / nü",
    practiceWords: ["绿", "女", "旅"],
    isCustom: false,
  },
  {
    id: "F002",
    category: "final" as const,
    commonError: "Mandarin e pronounced like English uh",
    example: "饿 (è)",
    scientificExplanation: "Mandarin e /ɤ/ is a mid-back unrounded vowel, not the English schwa /ə/.",
    simpleExplanation: "Your mouth is too relaxed and low.",
    howToFix: "Pull the tongue back into the throat, keeping it high-mid. Keep the sound full, not relaxed.",
    minimalPairs: "e / a, he / ha, de / da",
    practiceWords: ["饿", "喝", "的"],
    isCustom: false,
  },
  {
    id: "F003",
    category: "final" as const,
    commonError: "-eng nasal ending dropped or replaced with -en",
    example: "冷 (lěng)",
    scientificExplanation: "The final -eng /əŋ/ ends with a velar nasal ŋ, not n.",
    simpleExplanation: "The sound should end in the back of the mouth, not the front.",
    howToFix: "Say \"ng\" like the end of sing. Keep the tongue back. Don't touch the teeth like n.",
    minimalPairs: "en / eng, ben / beng, sen / seng",
    practiceWords: ["冷", "风", "能"],
    isCustom: false,
  },
  {
    id: "F004",
    category: "final" as const,
    commonError: "-ian pronounced like -yan",
    example: "先 (xiān)",
    scientificExplanation: "-ian /iɛn/ contains a glide from i → ɛ before the nasal.",
    simpleExplanation: "You're skipping the middle vowel (ɛ). To produce /ɛ/, open your mouth to a half-open position, with your lips unrounded and slightly stretched.",
    howToFix: "Think of it as three steps: i → ɛ → n. Open the mouth slightly after i.",
    minimalPairs: "ian / yan, xian / xuan",
    practiceWords: ["先", "天", "边"],
    isCustom: false,
  },
  {
    id: "F005",
    category: "final" as const,
    commonError: "-uo simplified to o",
    example: "多 (duō)",
    scientificExplanation: "Mandarin -uo /uo/ is a diphthong, not a single vowel.",
    simpleExplanation: "Your mouth should move from u → o.",
    howToFix: "Start with u (rounded lips). Open slightly into o.",
    minimalPairs: "uo / o, duo / do",
    practiceWords: ["多", "国", "火"],
    isCustom: false,
  },
  {
    id: "F006",
    category: "final" as const,
    commonError: "-ong pronounced like -on",
    example: "东 (dōng)",
    scientificExplanation: "The final -ong /ʊŋ/ ends with a velar nasal ŋ.",
    simpleExplanation: "Finish the sound in the back of your mouth.",
    howToFix: "on / ong, don / dong, ton / tong",
    minimalPairs: "on / ong, don / dong, ton / tong",
    practiceWords: ["东", "空", "龙"],
    isCustom: false,
  },
  {
    id: "F007",
    category: "final" as const,
    commonError: "-ai pronounced like English eye",
    example: "爱 (ài)",
    scientificExplanation: "Mandarin ai /aɪ/ begins with a low central vowel, longer than the English \"eye.\"",
    simpleExplanation: "Start with a wide open \"a\", higher than you would when pronouncing the English \"eye.\"",
    howToFix: "Open your mouth wider at the start, and make the diphthong last longer.",
    minimalPairs: "a / ai, ba / bai, da / dai",
    practiceWords: ["爱", "白", "来"],
    isCustom: false,
  },
  {
    id: "F008",
    category: "final" as const,
    commonError: "-iao reduced without full glide",
    example: "小 (xiǎo)",
    scientificExplanation: "-iao /iau/ has two glides.",
    simpleExplanation: "Your mouth should move: i → a → o",
    howToFix: "Slow it down. Follow all three positions: i → a → o.",
    minimalPairs: "iao / ao",
    practiceWords: ["小", "叫", "条"],
    isCustom: false,
  },
  {
    id: "F009",
    category: "final" as const,
    commonError: "Er-hua error",
    example: "门儿",
    scientificExplanation: "Erhua (儿化) is a rhotic suffix that modifies the vowel of the preceding syllable.\n\nWhen the original syllable ends in a nasal consonant (-n or -ng), the nasal is usually dropped and replaced by rhoticization.",
    simpleExplanation: "When you add -儿, the preceding syllable's n or ng sound disappears.\n\nSo: 门儿 mén + ér → mér\nIt should sound like one syllable with an \"r\" sound at the end, not two syllables.\n\nIncorrect: ménér",
    howToFix: "Say the word without the final -n.\n\nCurl your tongue tip slightly back.\n\nAdd a light r-coloring to the vowel.\n\nSteps: mén → mé → mér",
    minimalPairs: null,
    practiceWords: ["门儿", "玩儿", "花儿"],
    isCustom: false,
  },
  {
    id: "F010",
    category: "final" as const,
    commonError: "-an and -ang confused",
    example: "饭 (fàn) vs 方 (fāng)",
    scientificExplanation: "-an /an/ ends with an alveolar nasal n (tongue tip touches the ridge behind upper teeth).\n\n-ang /aŋ/ ends with a velar nasal ŋ (tongue back rises to soft palate).\n\nLearners often use one ending in both contexts, collapsing the contrast.",
    simpleExplanation: "-an ends with the tip of your tongue touching the roof of your mouth, like English \"can\".\n\n-ang ends with the back of your tongue, like the end of \"song\".\n\nThey're not interchangeable — native speakers clearly hear the difference.",
    howToFix: "For -an: close your lips slightly, tongue tip touches the upper ridge, sound closes at the front.\n\nFor -ang: keep your mouth open a little longer, let the sound fade at the back of your throat without touching the front.\n\nDrill minimal pairs slowly: fàn / fāng, kàn / kāng.",
    minimalPairs: "饭 / 方, 看 / 康, 班 / 帮, 安 / 昂",
    practiceWords: ["饭", "方", "看", "康"],
    isCustom: false,
  },
  {
    id: "F011",
    category: "final" as const,
    commonError: "-ao glide not fully completed",
    example: "好 (hǎo)",
    scientificExplanation: "-ao /au/ is a diphthong that glides from a low open vowel /a/ to a high back rounded vowel /u/.\n\nLearners often truncate the glide, producing only the /a/ part or a short /ao/ without fully rounding the lips at the end.",
    simpleExplanation: "Your mouth starts open (like \"ah\") but doesn't round into the \"o/w\" sound at the end.\n\nThe whole glide should travel from open to rounded.",
    howToFix: "Start with your mouth wide open — \"aaa\".\n\nThen gradually bring your lips into a rounded position (like saying \"o\" or \"oo\").\n\nThe ending doesn't need to be a full \"o\" — just a noticeable rounding movement.",
    minimalPairs: "好 / 哈, 猫 / 嘛, 包 / 八",
    practiceWords: ["好", "猫", "包", "到"],
    isCustom: false,
  },
  {
    id: "F012",
    category: "final" as const,
    commonError: "-ui simplified — the u glide is dropped",
    example: "对 (duì)",
    scientificExplanation: "-ui is short for -uei /uei/: a sequence of rounded vowel /u/ → mid vowel /e/ → high front /i/.\n\nLearners often reduce this to just /i/ or /ei/, dropping the initial rounded glide.",
    simpleExplanation: "You're skipping the \"w\" rounding at the start.\n\n-ui sounds like \"way\" in English, but with a tighter \"oo\" start — not just \"-i\" or \"-ee\".",
    howToFix: "Before the vowel, briefly round your lips as if saying \"w\" or \"oo\".\n\nThen glide through the middle vowel to end on \"ee\".\n\nFull path: u → e → i (or roughly: oo → eh → ee).",
    minimalPairs: "对 / 的, 会 / 和, 水 / 四",
    practiceWords: ["对", "会", "水", "退"],
    isCustom: false,
  },
  {
    id: "F013",
    category: "final" as const,
    commonError: "-un simplified — the u glide is dropped",
    example: "春 (chūn)",
    scientificExplanation: "-un is short for -uen /uən/: starting with rounded /u/, moving through a mid vowel, and ending with alveolar nasal /n/.\n\nLearners often reduce this to -en or skip the initial u/w rounding.",
    simpleExplanation: "Like -ui, you're missing the rounded \"oo\" start before the nasal ending.\n\n-un should start with rounded lips (like \"oo\") then close into \"-n\".",
    howToFix: "Round your lips as if saying \"oo\" first.\n\nThen say \"-en\" (middle vowel + nasal).\n\nCombined: \"oo\" + \"en\" → \"uen\" said quickly.\n\nMake sure the rounded onset is there.",
    minimalPairs: "春 / 陈, 论 / 林, 村 / 参",
    practiceWords: ["春", "论", "村", "婚"],
    isCustom: false,
  },
  {
    id: "F014",
    category: "final" as const,
    commonError: "üe mispronounced — ü sounds like u",
    example: "月 (yuè)",
    scientificExplanation: "üe /yɛ/ begins with the front rounded vowel ü /y/ (like German ü or French u), which does not exist in English.\n\nLearners typically replace ü with a back rounded /u/, making üe sound like \"weh\" instead of the correct front-rounded \"üeh\".",
    simpleExplanation: "The ü in üe is like saying \"ee\" while rounding your lips — it's not the same as \"oo\".\n\nMost English speakers substitute the easier back-rounded \"u\", which makes the syllable sound off.",
    howToFix: "Start by saying \"ee\" (as in \"see\"). Hold that tongue position.\n\nNow round your lips while keeping your tongue where it is.\n\nThat's ü. Now add \"eh\" (open vowel) after it.\n\nü + eh = üe.",
    minimalPairs: "月 / 喂, 学 / 说, 雪 / 说",
    practiceWords: ["月", "学", "雪", "缺"],
    isCustom: false,
  },

  {
    id: "F015",
    category: "final" as const,
    commonError: "-ing nasal ending dropped or replaced with -in",
    example: "星 (xīng)",
    scientificExplanation: "The final -ing /iŋ/ ends with a velar nasal ŋ (tongue back rises to soft palate).\n\n-in /in/ ends with an alveolar nasal n (tongue tip touches the ridge behind the upper teeth).\n\nLearners often substitute the more familiar alveolar n, closing the syllable at the front of the mouth instead of the back.",
    simpleExplanation: "The ending should happen at the back of your mouth — not the front.\n\n-in ends with your tongue tip touching behind your upper teeth (like English \"in\").\n-ing ends with the back of your tongue lifting up toward your throat (like English \"sing\").",
    howToFix: "Say the English word \"sing\" and hold the final nasal sound — that's ŋ.\n\nNow replace the vowel: si... + ŋ = xīng.\n\nFeel the back of your tongue making contact, not the front.\n\nDrill minimal pairs: xīn / xīng, lín / líng, jīn / jīng.",
    minimalPairs: "心 / 星, 林 / 灵, 金 / 京, 亲 / 青",
    practiceWords: ["心", "信", "林", "金"],
    isCustom: false,
  },

  // ─── INITIALS (additional) ─────────────────────────────────────────────────
  {
    id: "I011",
    category: "initial" as const,
    commonError: "s and sh not clearly distinguished",
    example: "四 (sì) vs 是 (shì)",
    scientificExplanation: "Mandarin s /s/ is a voiceless alveolar fricative: tongue tip near the upper teeth ridge, NOT curled back.\n\nMandarin sh /ʂ/ is a voiceless retroflex fricative: tongue tip curled slightly back.\n\nLearners who have practised retroflex consonants sometimes overcorrect and apply retroflexion to s, blurring the s/sh contrast.",
    simpleExplanation: "You may be curling your tongue for s when it should stay flat.\n\ns is tongue flat and forward — like English \"s\".\n\nsh is tongue curled slightly back.",
    howToFix: "For s: keep your tongue tip flat, just behind your upper teeth. Do NOT curl it.\n\nFor sh: curl the tongue tip slightly back toward the roof of your mouth.\n\nDrill: sì / shì, sān / shān, sāo / shāo.",
    minimalPairs: "四 / 是, 三 / 山, 扫 / 烧",
    practiceWords: ["四", "是", "三", "山"],
    isCustom: false,
  },
  {
    id: "I012",
    category: "initial" as const,
    commonError: "n and l confused",
    example: "那 (nà) vs 啦 (la)",
    scientificExplanation: "Mandarin n /n/ is a voiced alveolar nasal: airflow exits through the nose, tongue tip touches the upper alveolar ridge.\n\nMandarin l /l/ is a voiced alveolar lateral: airflow exits around the sides of the tongue, which blocks the centre.\n\nLearners often confuse these two, especially those from Southern Chinese dialect backgrounds or whose native language doesn't distinguish them.",
    simpleExplanation: "Both n and l look similar in the mouth, but the difference is where the air goes:\n\nn → air out through the nose (hum it: mmmm-n)\nl → air out around the sides of the tongue (tongue tip stays up in the centre)",
    howToFix: "For n: touch your tongue tip to the ridge behind upper teeth. Let air hum out through your nose.\n\nFor l: same tongue position, but close off the nose and let air flow around the sides of your tongue.\n\nTry: nā vs lā — feel the nasal hum for n but not for l.",
    minimalPairs: "那 / 啦, 女 / 旅, 年 / 连, 牛 / 流",
    practiceWords: ["那", "啦", "年", "连"],
    isCustom: false,
  },
  {
    id: "I013",
    category: "initial" as const,
    commonError: "d/t aspiration contrast not clear",
    example: "大 (dà) vs 他 (tā)",
    scientificExplanation: "Mandarin contrasts unaspirated d /t/ and aspirated t /tʰ/.\n\nd is voiceless unaspirated: no burst of air after release.\nt is voiceless aspirated: strong burst of air after release.\n\nEnglish speakers often add voicing to d (making it like English d) and/or underaspirate t, blurring the distinction.",
    simpleExplanation: "Mandarin d/t is about air puff, not voicing:\n\nd = very soft \"t\" sound — almost no air comes out\nt = strong \"t\" with a clear puff of air",
    howToFix: "d: put your tongue on the alveolar ridge, release softly with no air burst. Think: soft and tight.\n\nt: same position, but release with a strong puff of air. Think: burst open.\n\nHold a piece of paper: it should move with t but barely with d.",
    minimalPairs: "大 / 他, 地 / 题, 道 / 套",
    practiceWords: ["大", "他", "地", "题"],
    isCustom: false,
  },
  {
    id: "I014",
    category: "initial" as const,
    commonError: "g/k aspiration contrast not clear",
    example: "哥 (gē) vs 可 (kě)",
    scientificExplanation: "Mandarin contrasts unaspirated g /k/ and aspirated k /kʰ/, both voiceless velar stops.\n\ng is voiceless unaspirated: the back of the tongue touches the soft palate, released without a burst of air.\n\nk is voiceless aspirated: same position but with a strong burst of air.\n\nEnglish speakers often voice g (like English g) or under-aspirate k.",
    simpleExplanation: "Like d/t, Mandarin g and k are not about voicing — they're about air:\n\ng = no air puff\nk = strong air puff",
    howToFix: "g: press the back of your tongue against the soft palate, release without blowing air. Keep it voiceless.\n\nk: same position, but release with a sharp burst of air.\n\nDrill: gē / kě, gāo / kāo — feel the difference in airflow.",
    minimalPairs: "哥 / 可, 高 / 考, 国 / 阔",
    practiceWords: ["哥", "可", "高", "考"],
    isCustom: false,
  },
  {
    id: "I015",
    category: "initial" as const,
    commonError: "h too harsh or inconsistent",
    example: "好 (hǎo)",
    scientificExplanation: "Mandarin h /x/ is a voiceless velar fricative: the back of the tongue comes close to the soft palate, creating friction as air passes through.\n\nIt is stronger and more guttural than English h /h/, which is a simple glottal fricative with minimal friction.\n\nLearners sometimes substitute English h (too soft) or produce an overly harsh German-style ch (too strong).",
    simpleExplanation: "English \"h\" is basically just a soft breath.\n\nMandarin h has more friction — it comes from the back of the throat, like a gentle clearing of the throat.\n\nThink of it as halfway between English \"h\" and the sound in \"Bach\" (German).",
    howToFix: "Place the back of your tongue near your soft palate.\n\nPush air through the narrow gap to create friction — you should feel it in the back of your throat.\n\nDon't go too far: it should sound like a strong breathy h, not a full gargling sound.\n\nPractice: hā, hē, hū — feel the consistent friction.",
    minimalPairs: "好 / 奥, 喝 / 饿, 号 / 傲",
    practiceWords: ["好", "喝", "号", "河"],
    isCustom: false,
  },
];

export async function seedPronunciationErrors() {
  const existing = await db.select({ id: pronunciationErrors.id }).from(pronunciationErrors);
  const existingIds = new Set(existing.map(e => e.id));
  const toInsert = SEED_ERRORS.filter(e => !existingIds.has(e.id));

  if (toInsert.length === 0) return;

  console.log(`[seed] Adding ${toInsert.length} new pronunciation error(s)...`);
  await db.insert(pronunciationErrors).values(toInsert);
  console.log(`[seed] Done. Total seed errors: ${SEED_ERRORS.length}.`);
}
